# ERT tests

name: ert
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Install Emacs
      run: sudo apt-get update && sudo apt-get install -y emacs && emacs --version
        
    - name: Run tests
      run: emacs -batch -l ert -l snap-indent.el -l snap-indent-tests.el -f ert-run-tests-batch-and-exit
